name: Docs

on:
  push:
    branches:
      - "main"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install package with dev dependancies
        run: pip install -e .[dev]
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          clean: false
          ref: 'gh-pages'
      - name: Commit documentation changes
        run: |
          cp -r docs/_build/html/* ./

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[CI] Update documentation"
          git push
